# SavageFactions Default Permissions Addon,
# Made with <3


default-perms-allow:
  recruit:
    - door
    - button
    - lever
    - items
    - fly
  normal:
    - build
    - destroy
    - door
    - button
    - lever
    - items
    - fly
    - container
    - warp
    - chest
    - home
  mod:
    - build
    - destroy
    - door
    - button
    - lever
    - items
    - fly
    - container
    - warp
    - chest
    - territory
    - sethome
    - setwarp
    - vault
    - tntbank
    - tntfill
    - kick
    - invite
  coleader:
    - build
    - destroy
    - door
    - button
    - lever
    - items
    - fly
    - container
    - warp
    - chest
    - territory
    - sethome
    - setwarp
    - vault
    - tntbank
    - tntfill
    - kick
    - invite
    - ban
    - promote
    - withdraw
    - access
  truce:
    - fly
  ally:
    - fly
  enemy:
  neutral:

default-perms-deny:
  recruit:
    - build
    - destroy
    - frostwalk
    - painbuild
    - container
    - invite
    - kick
    - sethome
    - withdraw
    - territory
    - access
    - promote
    - setwarp
    - warp
    - ban
    - disband
    - spawner
    - tntbank
    - vault
    - tntfill
    - chest
    - home
  normal:
    - frostwalk
    - painbuild
    - invite
    - kick
    - sethome
    - withdraw
    - territory
    - access
    - promote
    - setwarp
    - ban
    - disband
    - spawner
    - tntbank
    - vault
    - tntfill
  mod:
    - frostwalk
    - painbuild
    - withdraw
    - access
    - promote
    - ban
    - disband
    - spawner
  coleader:
    - disband
    - spawner
  truce:
    - ban
    - build
    - destroy
    - frostwalk
    - painbuild
    - door
    - button
    - lever
    - container
    - invite
    - kick
    - items
    - sethome
    - territory
    - access
    - home
    - disband
    - promote
    - setwarp
    - warp
    - vault
    - tntbank
    - tntfill
    - withdraw
    - chest
    - spawner
  ally:
    - ban
    - build
    - destroy
    - frostwalk
    - painbuild
    - door
    - button
    - lever
    - container
    - invite
    - kick
    - items
    - sethome
    - territory
    - access
    - home
    - disband
    - promote
    - setwarp
    - warp
    - vault
    - tntbank
    - tntfill
    - withdraw
    - chest
    - spawner
  enemy:
    - ban
    - build
    - destroy
    - frostwalk
    - painbuild
    - door
    - button
    - lever
    - container
    - invite
    - kick
    - items
    - sethome
    - territory
    - access
    - home
    - disband
    - promote
    - setwarp
    - warp
    - vault
    - fly
    - tntbank
    - tntfill
    - withdraw
    - chest
    - spawner
  neutral:
    - ban
    - build
    - destroy
    - frostwalk
    - painbuild
    - door
    - button
    - lever
    - container
    - invite
    - kick
    - items
    - sethome
    - territory
    - access
    - home
    - disband
    - promote
    - setwarp
    - warp
    - fly
    - vault
    - tntbank
    - tntfill
    - withdraw
    - chest
    - spawner


